export const DEFAULT_PASSPORT_BADGES = [
  {
    slug: "rapa-nui",
    name: "Isla de Pascua",
    destination: "Rapa Nui",
    description: "Has explorado el ombligo del mundo",
    image: "",
    emoji: "🗿",
    matchTerms: JSON.stringify(["rapa nui", "isla de pascua", "easter island"]),
    sortOrder: 1,
  },
  {
    slug: "atacama",
    name: "Desierto de Atacama",
    destination: "Atacama",
    description: "Aventura bajo las estrellas del desierto más árido",
    image: "",
    emoji: "🏜️",
    matchTerms: JSON.stringify(["atacama", "san pedro"]),
    sortOrder: 2,
  },
  {
    slug: "patagonia",
    name: "Patagonia",
    destination: "Patagonia",
    description: "Glaciares y naturaleza extrema",
    image: "",
    emoji: "🏔️",
    matchTerms: JSON.stringify(["patagonia", "torres del paine", "punta arenas"]),
    sortOrder: 3,
  },
  {
    slug: "machu-picchu",
    name: "Machu Picchu",
    destination: "Perú",
    description: "La ciudadela inca te esperó",
    image: "",
    emoji: "⛰️",
    matchTerms: JSON.stringify(["machu picchu", "cusco", "peru", "perú"]),
    sortOrder: 4,
  },
  {
    slug: "elqui",
    name: "Valle de Elqui",
    destination: "Elqui",
    description: "Cielos estrellados y pisco",
    image: "",
    emoji: "✨",
    matchTerms: JSON.stringify(["elqui", "la serena", "coquimbo"]),
    sortOrder: 5,
  },
];
