export const DEFAULT_PASSPORT_BADGES = [
  {
    slug: "rapa-nui",
    name: "Isla de Pascua",
    destination: "Rapa Nui",
    description: "Has explorado el ombligo del mundo",
    image: "",
    emoji: "🗿",
    matchTerms: JSON.stringify([
      "rapa nui",
      "rapa-nui",
      "group-rapa-nui",
      "isla de pascua",
      "easter island",
    ]),
    sortOrder: 1,
  },
  {
    slug: "atacama",
    name: "Desierto de Atacama",
    destination: "Atacama",
    description: "Aventura bajo las estrellas del desierto más árido",
    image: "",
    emoji: "🏜️",
    matchTerms: JSON.stringify([
      "atacama",
      "san pedro",
      "san-pedro-uyuni",
      "group-atacama",
      "group-uyuni",
      "region-atacama",
      "uyuni",
    ]),
    sortOrder: 2,
  },
  {
    slug: "patagonia",
    name: "Patagonia",
    destination: "Patagonia",
    description: "Glaciares y naturaleza extrema",
    image: "",
    emoji: "🏔️",
    matchTerms: JSON.stringify([
      "patagonia",
      "torres del paine",
      "punta arenas",
      "catedrales-marmol",
      "catedrales",
    ]),
    sortOrder: 3,
  },
  {
    slug: "machu-picchu",
    name: "Machu Picchu",
    destination: "Perú",
    description: "La ciudadela inca te esperó",
    image: "",
    emoji: "⛰️",
    matchTerms: JSON.stringify([
      "machu picchu",
      "machu-picchu",
      "cusco-machupicchu",
      "cusco",
      "peru",
      "perú",
    ]),
    sortOrder: 4,
  },
  {
    slug: "elqui",
    name: "Valle de Elqui",
    destination: "Elqui",
    description: "Cielos estrellados y pisco",
    image: "",
    emoji: "✨",
    matchTerms: JSON.stringify([
      "elqui",
      "ballenas-elqui",
      "la serena",
      "coquimbo",
      "vicuna",
    ]),
    sortOrder: 5,
  },
  {
    slug: "rio-de-janeiro",
    name: "Río de Janeiro",
    destination: "Río de Janeiro",
    description: "Cristo, playas y samba",
    image: "",
    emoji: "🇧🇷",
    matchTerms: JSON.stringify([
      "rio de janeiro",
      "rio-de-janeiro",
      "río de janeiro",
      "copacabana",
      "ipanema",
    ]),
    sortOrder: 6,
  },
  {
    slug: "ilha-grande",
    name: "Ilha Grande",
    destination: "Ilha Grande",
    description: "Paraíso verde frente al Atlántico",
    image: "",
    emoji: "🏝️",
    matchTerms: JSON.stringify([
      "ilha grande",
      "ilha-grande",
      "isla grande",
      "angra dos reis",
    ]),
    sortOrder: 7,
  },
  {
    slug: "iguazu",
    name: "Cataratas del Iguazú",
    destination: "Iguazú",
    description: "La fuerza del agua en la triple frontera",
    image: "",
    emoji: "💧",
    matchTerms: JSON.stringify([
      "iguazu",
      "iguazú",
      "iguassu",
      "cataratas",
      "foz do iguacu",
      "foz do iguaçu",
      "puerto iguazu",
    ]),
    sortOrder: 8,
  },
];
