#!/usr/bin/env python3
"""
Universo Nomada - Plan Estrategico de Automatizacion y Crecimiento
Professional PDF Report Generation
"""

import os
import sys
import hashlib
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch, cm
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY, TA_RIGHT
from reportlab.lib import colors
from reportlab.platypus import (
    Paragraph, Spacer, Table, TableStyle, PageBreak,
    KeepTogether, CondPageBreak, Image as RLImage
)
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.platypus import SimpleDocTemplate
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from pypdf import PdfReader, PdfWriter, Transformation

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# COLOR PALETTE (auto-generated by pdf.py palette.cascade)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PAGE_BG       = colors.HexColor('#f5f5f4')
SECTION_BG    = colors.HexColor('#eeedec')
CARD_BG       = colors.HexColor('#ebe9e6')
TABLE_STRIPE  = colors.HexColor('#f4f4f2')
HEADER_FILL   = colors.HexColor('#4c4735')
COVER_BLOCK   = colors.HexColor('#5a5443')
BORDER        = colors.HexColor('#d6d0be')
ICON          = colors.HexColor('#947e3c')
ACCENT        = colors.HexColor('#633dd4')
ACCENT_2      = colors.HexColor('#56c48d')
TEXT_PRIMARY   = colors.HexColor('#161514')
TEXT_MUTED     = colors.HexColor('#8d8b84')
SEM_SUCCESS   = colors.HexColor('#467957')
SEM_WARNING   = colors.HexColor('#937841')
SEM_ERROR     = colors.HexColor('#ac4b42')
SEM_INFO      = colors.HexColor('#45688a')

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# FONT REGISTRATION
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
pdfmetrics.registerFont(TTFont('TimesNewRoman', '/usr/share/fonts/truetype/english/Times-New-Roman.ttf'))
pdfmetrics.registerFont(TTFont('Calibri', '/usr/share/fonts/truetype/english/calibri-regular.ttf'))
pdfmetrics.registerFont(TTFont('SimHei', '/usr/share/fonts/truetype/chinese/SimHei.ttf'))
pdfmetrics.registerFont(TTFont('MicrosoftYaHei', '/usr/share/fonts/truetype/chinese/msyh.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans', '/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf'))

registerFontFamily('TimesNewRoman', normal='TimesNewRoman', bold='TimesNewRoman')
registerFontFamily('Calibri', normal='Calibri', bold='Calibri')
registerFontFamily('SimHei', normal='SimHei', bold='SimHei')

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# PAGE SETUP
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PAGE_W, PAGE_H = A4
LEFT_MARGIN = 1.0 * inch
RIGHT_MARGIN = 1.0 * inch
TOP_MARGIN = 0.8 * inch
BOTTOM_MARGIN = 0.8 * inch
AVAILABLE_WIDTH = PAGE_W - LEFT_MARGIN - RIGHT_MARGIN

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# STYLES
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# H1 Style
h1_style = ParagraphStyle(
    name='H1',
    fontName='TimesNewRoman',
    fontSize=20,
    leading=26,
    textColor=ACCENT,
    spaceBefore=18,
    spaceAfter=12,
    alignment=TA_LEFT,
)

# H2 Style
h2_style = ParagraphStyle(
    name='H2',
    fontName='TimesNewRoman',
    fontSize=15,
    leading=20,
    textColor=HEADER_FILL,
    spaceBefore=14,
    spaceAfter=8,
    alignment=TA_LEFT,
)

# H3 Style
h3_style = ParagraphStyle(
    name='H3',
    fontName='TimesNewRoman',
    fontSize=12,
    leading=16,
    textColor=SEM_INFO,
    spaceBefore=10,
    spaceAfter=6,
    alignment=TA_LEFT,
)

# Body text
body_style = ParagraphStyle(
    name='Body',
    fontName='Calibri',
    fontSize=10.5,
    leading=17,
    textColor=TEXT_PRIMARY,
    spaceBefore=0,
    spaceAfter=8,
    alignment=TA_JUSTIFY,
    firstLineIndent=0,
)

# Bullet style
bullet_style = ParagraphStyle(
    name='Bullet',
    fontName='Calibri',
    fontSize=10.5,
    leading=17,
    textColor=TEXT_PRIMARY,
    spaceBefore=2,
    spaceAfter=4,
    leftIndent=20,
    bulletIndent=8,
    alignment=TA_LEFT,
)

# Callout style
callout_style = ParagraphStyle(
    name='Callout',
    fontName='Calibri',
    fontSize=11,
    leading=17,
    textColor=ACCENT,
    spaceBefore=8,
    spaceAfter=8,
    leftIndent=24,
    borderPadding=6,
    alignment=TA_LEFT,
)

# Table header style
table_header_style = ParagraphStyle(
    name='TableHeader',
    fontName='TimesNewRoman',
    fontSize=10,
    leading=14,
    textColor=colors.white,
    alignment=TA_CENTER,
)

# Table cell style
table_cell_style = ParagraphStyle(
    name='TableCell',
    fontName='Calibri',
    fontSize=9.5,
    leading=14,
    textColor=TEXT_PRIMARY,
    alignment=TA_LEFT,
)

table_cell_center = ParagraphStyle(
    name='TableCellCenter',
    fontName='Calibri',
    fontSize=9.5,
    leading=14,
    textColor=TEXT_PRIMARY,
    alignment=TA_CENTER,
)

# Caption style
caption_style = ParagraphStyle(
    name='Caption',
    fontName='Calibri',
    fontSize=9,
    leading=13,
    textColor=TEXT_MUTED,
    alignment=TA_CENTER,
    spaceBefore=3,
    spaceAfter=6,
)

# TOC styles
toc_h1_style = ParagraphStyle(
    name='TOCH1',
    fontName='TimesNewRoman',
    fontSize=13,
    leading=20,
    leftIndent=20,
    textColor=TEXT_PRIMARY,
)

toc_h2_style = ParagraphStyle(
    name='TOCH2',
    fontName='Calibri',
    fontSize=11,
    leading=18,
    leftIndent=40,
    textColor=TEXT_MUTED,
)

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# TOC DOCUMENT TEMPLATE
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            self.notify('TOCEntry', (level, text, self.page, key))

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# HELPER FUNCTIONS
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
def add_heading(text, style, level=0):
    key = 'h_%s' % hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph('<a name="%s"/><b>%s</b>' % (key, text), style)
    p.bookmark_name = text
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p

H1_ORPHAN_THRESHOLD = (PAGE_H - TOP_MARGIN - BOTTOM_MARGIN) * 0.15

def add_major_section(text):
    return [
        CondPageBreak(H1_ORPHAN_THRESHOLD),
        add_heading(text, h1_style, level=0),
    ]

def add_subsection(text):
    return [add_heading(text, h2_style, level=1)]

def add_sub3(text):
    return [add_heading(text, h3_style, level=2)]

def body(text):
    return Paragraph(text, body_style)

def bullet(text):
    return Paragraph(text, bullet_style)

def callout(text):
    return Paragraph('<b>%s</b>' % text, callout_style)

def make_table(data, col_widths, caption_text=None):
    """Create a styled table with proper formatting."""
    t = Table(data, colWidths=col_widths, hAlign='CENTER')
    style_cmds = [
        ('BACKGROUND', (0, 0), (-1, 0), HEADER_FILL),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ]
    # Alternating row colors
    for i in range(1, len(data)):
        bg = colors.white if i % 2 == 1 else TABLE_STRIPE
        style_cmds.append(('BACKGROUND', (0, i), (-1, i), bg))
    t.setStyle(TableStyle(style_cmds))
    elements = [Spacer(1, 18), t]
    if caption_text:
        elements.append(Spacer(1, 6))
        elements.append(Paragraph(caption_text, caption_style))
    elements.append(Spacer(1, 18))
    return elements

def safe_keep_together(elements):
    total_h = 0
    for el in elements:
        w, h = el.wrap(AVAILABLE_WIDTH, PAGE_H)
        total_h += h
    MAX_KEEP_HEIGHT = PAGE_H * 0.4
    if total_h <= MAX_KEEP_HEIGHT:
        return [KeepTogether(elements)]
    elif len(elements) >= 2:
        return [KeepTogether(elements[:2])] + list(elements[2:])
    else:
        return list(elements)

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# COVER HTML (Template 03 - The Monolith)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
COVER_HTML = """<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="UTF-8">
<title>Universo Nomada - Plan Estrategico</title>
<link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;700;900&family=Inter:wght@300;400;500;600&display=swap" rel="stylesheet">
<style>
  @page { size: 794px 1123px; margin: 0; }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  html, body { width: 794px; height: 1123px; overflow: hidden; background: #fafaf8; }

  .cover {
    position: relative;
    width: 794px;
    height: 1123px;
    background: #fafaf8;
  }

  /* Layer 1 - Background */
  .bg-layer {
    position: absolute;
    inset: 0;
    overflow: hidden;
    z-index: 1;
  }
  .watermark {
    position: absolute;
    right: -20px;
    top: 50%;
    transform: translateY(-50%) rotate(90deg);
    font-family: 'Playfair Display', serif;
    font-size: 180px;
    font-weight: 900;
    color: #4c4735;
    opacity: 0.03;
    white-space: nowrap;
    letter-spacing: 8px;
  }

  /* Layer 2 - Structure */
  .struct-layer {
    position: absolute;
    inset: 0;
    z-index: 2;
  }
  .color-dash {
    position: absolute;
    left: 0.12 * 794px;
    left: 95px;
    top: 0.15 * 1123px;
    top: 168px;
    width: 50px;
    height: 5px;
    background: #633dd4;
  }
  .meta-line {
    position: absolute;
    left: 95px;
    bottom: 200px;
    width: 2px;
    height: 100px;
    background: #4c4735;
    opacity: 0.5;
  }

  /* Layer 3 - Content */
  .content-layer {
    position: absolute;
    inset: 0;
    z-index: 3;
    padding-left: 95px;
  }

  .kicker {
    position: absolute;
    left: 95px;
    top: 195px;
    font-family: 'Inter', sans-serif;
    font-size: 16px;
    font-weight: 400;
    letter-spacing: 3px;
    color: #4c4735;
    opacity: 0.6;
    text-transform: uppercase;
  }

  .hero-title {
    position: absolute;
    left: 95px;
    top: 230px;
    font-family: 'Playfair Display', serif;
    font-size: 52px;
    font-weight: 900;
    color: #161514;
    line-height: 1.15;
    max-width: 450px;
  }

  .summary {
    position: absolute;
    left: 95px;
    top: 500px;
    font-family: 'Inter', sans-serif;
    font-size: 16px;
    font-weight: 400;
    color: #161514;
    opacity: 0.85;
    line-height: 1.6;
    max-width: 420px;
  }

  .meta {
    position: absolute;
    left: 95px;
    top: 760px;
    font-family: 'Inter', sans-serif;
    font-size: 18px;
    font-weight: 400;
    color: #8d8b84;
    line-height: 2.0;
  }

  .footer {
    position: absolute;
    right: 50px;
    bottom: 60px;
    font-family: 'Inter', sans-serif;
    font-size: 14px;
    font-weight: 400;
    color: #4c4735;
    opacity: 0.5;
    text-align: right;
  }
</style>
</head>
<body>
<div class="cover">
  <!-- Layer 1: Background -->
  <div class="bg-layer">
    <div class="watermark">NOMADA</div>
  </div>

  <!-- Layer 2: Structure -->
  <div class="struct-layer">
    <div class="color-dash"></div>
    <div class="meta-line"></div>
  </div>

  <!-- Layer 3: Content -->
  <div class="content-layer">
    <div class="kicker">PLAN ESTRATEGICO 2026</div>
    <div class="hero-title">Universo<br/>Nomada</div>
    <div class="summary">Analisis integral, automatizacion de procesos y estrategia de crecimiento para multiplicar las ventas de tu agencia boutique de viajes en La Serena, Chile.</div>
    <div class="meta">
      La Serena, Chile<br/>
      Abril 2026<br/>
      Documento Confidencial
    </div>
    <div class="footer">
      Automatizacion + Ventas<br/>
      +100% Crecimiento
    </div>
  </div>
</div>
</body>
</html>
"""

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# BUILD PDF
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
OUTPUT_DIR = '/home/z/my-project/download'
BODY_PDF = os.path.join(OUTPUT_DIR, 'universo_nomada_body.pdf')
COVER_PDF = os.path.join(OUTPUT_DIR, 'universo_nomada_cover.pdf')
FINAL_PDF = os.path.join(OUTPUT_DIR, 'Universo_Nomada_Plan_Estrategico.pdf')
COVER_HTML_PATH = os.path.join(OUTPUT_DIR, 'cover_universo_nomada.html')

# Write cover HTML
with open(COVER_HTML_PATH, 'w', encoding='utf-8') as f:
    f.write(COVER_HTML)

# Build body PDF
doc = TocDocTemplate(
    BODY_PDF,
    pagesize=A4,
    leftMargin=LEFT_MARGIN,
    rightMargin=RIGHT_MARGIN,
    topMargin=TOP_MARGIN,
    bottomMargin=BOTTOM_MARGIN,
    title='Universo Nomada - Plan Estrategico de Automatizacion y Crecimiento',
    author='Z.ai',
    creator='Z.ai',
)

story = []

# ── TABLE OF CONTENTS ──
story.append(Paragraph('<b>Indice de Contenidos</b>', ParagraphStyle(
    name='TOCTitle', fontName='TimesNewRoman', fontSize=18,
    leading=24, textColor=ACCENT, spaceAfter=12, alignment=TA_LEFT
)))
story.append(Spacer(1, 12))

toc = TableOfContents()
toc.levelStyles = [toc_h1_style, toc_h2_style]
story.append(toc)
story.append(PageBreak())

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# SECTION 1: DIAGNOSTICO ACTUAL
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
story.extend(add_major_section('1. Diagnostico Actual del Emprendimiento'))

story.append(body(
    'Universo Nomada se posiciona en el mercado como una agencia boutique de viajes que ofrece experiencias '
    'personalizadas, diferenciandose claramente de las agencias tradicionales que comercializan paquetes genericos. '
    'Su propuesta de valor se fundamenta en la cercania humana, donde cada cliente tiene un rostro y un nombre detras '
    'del servicio, generando una conexion emocional que las grandes corporaciones dificilmente pueden replicar. '
    'Esta filosofia de trabajo ha permitido construir una base de clientes leales que valoran la autenticidad y la '
    'atencion personalizada por encima de los descuentos masivos o las ofertas estandarizadas.'
))

story.append(body(
    'Sin embargo, este modelo de atencion altamente personalizado, si bien es una fortaleza diferenciadora, '
    'tambien constituye un cuello de botella operativo. Cada consulta, cada cotizacion, cada seguimiento requiere '
    'intervencion manual directa de la fundadora, lo que limita drasticamente la capacidad de escalar el negocio. '
    'Cuando el volumen de consultas aumenta, los tiempos de respuesta se alargan, la calidad del seguimiento '
    'disminuye y, en consecuencia, se pierden oportunidades de venta que un proceso mas automatizado podria capturar '
    'de manera eficiente y oportuna.'
))

story.append(body(
    'El hecho de que ahora un Ingeniero Comercial se incorpore al equipo representa una oportunidad estrategica '
    'significativa. No solo se suma capacidad de trabajo, sino que se anade una perspectiva profesional en ventas, '
    'analisis de mercado y gestion comercial que puede transformar radicalmente la forma en que Universo Nomada '
    'captura, nutre y convierte prospectos en clientes. La combinacion de la vision creativa y experiencial de la '
    'fundadora con la disciplina comercial del Ingeniero Comercial puede generar un efecto multiplicador sobre las '
    'ventas, siempre que se implementen los procesos y herramientas adecuados.'
))

# Positioning table
pos_data = [
    [Paragraph('<b>Atributo</b>', table_header_style),
     Paragraph('<b>Estado Actual</b>', table_header_style),
     Paragraph('<b>Impacto en Ventas</b>', table_header_style)],
    [Paragraph('Cercania humana', table_cell_style),
     Paragraph('Ventaja competitiva fuerte, pero dependiente de atencion manual', table_cell_style),
     Paragraph('Alto en fidelizacion, bajo en escalabilidad', table_cell_style)],
    [Paragraph('Experiencias autenticas', table_cell_style),
     Paragraph('Propuesta unica y diferenciada en el mercado', table_cell_style),
     Paragraph('Alto en conversion, requiere storytelling efectivo', table_cell_style)],
    [Paragraph('Flexibilidad a medida', table_cell_style),
     Paragraph('Proceso manual lento, sin templates ni sistema', table_cell_style),
     Paragraph('Medio: gusta al cliente pero retrasa la cotizacion', table_cell_style)],
    [Paragraph('Destinos seleccionados', table_cell_style),
     Paragraph('Curaduria valiosa, pero poca visibilidad online', table_cell_style),
     Paragraph('Bajo: los prospectos no descubren la oferta facilmente', table_cell_style)],
    [Paragraph('Acompanamiento constante', table_cell_style),
     Paragraph('Excelente servicio post-venta, pero consume mucho tiempo', table_cell_style),
     Paragraph('Alto en retencion, bajo en nuevas adquisiciones', table_cell_style)],
]
col_w = [AVAILABLE_WIDTH * 0.22, AVAILABLE_WIDTH * 0.42, AVAILABLE_WIDTH * 0.36]
story.extend(make_table(pos_data, col_w, 'Tabla 1: Analisis de atributos actuales y su impacto en ventas'))

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# SECTION 2: FODA
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
story.extend(add_major_section('2. Analisis FODA Estrategico'))

story.append(body(
    'El analisis FODA permite visualizar de manera clara la posicion competitiva de Universo Nomada en el mercado '
    'de turismo de experiencias en La Serena y la region de Coquimbo. Este diagnostico es fundamental para disenar '
    'las estrategias de automatizacion y crecimiento, ya que revela donde enfocar los recursos y que vulnerabilidades '
    'deben ser atendidas con urgencia antes de escalar las operaciones comerciales del negocio.'
))

foda_data = [
    [Paragraph('<b>Fortalezas</b>', table_header_style),
     Paragraph('<b>Debilidades</b>', table_header_style)],
    [Paragraph(
        '- Propuesta unica: experiencias personalizadas, no paquetes genericos<br/>'
        '- Alta fidelizacion: clientes que repiten y recomiendan<br/>'
        '- Cercania y confianza: rostro humano detras de la marca<br/>'
        '- Curaduria de destinos: seleccion autentica y diferenciada<br/>'
        '- Acompanamiento integral: desde la consulta hasta el viaje', table_cell_style),
     Paragraph(
        '- Procesos 100% manuales: cotizaciones, seguimiento, reservas<br/>'
        '- Dependencia de una sola persona para todas las operaciones<br/>'
        '- Ausencia de presencia digital estructurada (SEO, contenido)<br/>'
        '- Sin CRM ni sistema de gestion de clientes<br/>'
        '- Sin estrategia formal de captacion de leads online', table_cell_style)],
    [Paragraph('<b>Oportunidades</b>', table_header_style),
     Paragraph('<b>Amenazas</b>', table_header_style)],
    [Paragraph(
        '- Turismo en auge en region de Coquimbo y Valle del Elqui<br/>'
        '- Creciente demanda de turismo experiencial y sostenible<br/>'
        '- Mercado digital subexplotado por competidores locales<br/>'
        '- Incorporacion de Ing. Comercial al equipo<br/>'
        '- Tendencia de viajes personalizados post-pandemia', table_cell_style),
     Paragraph(
        '- Competidores grandes con mayor presupuesto en marketing digital<br/>'
        '- Plataformas OTA (Booking, Airbnb) capturan busquedas directas<br/>'
        '- Estacionalidad turistica marcada en la region<br/>'
        '- Sensibilidad al precio en segmento medio del mercado<br/>'
        '- Riesgo de saturacion si no se automatiza antes de crecer', table_cell_style)],
]
foda_col = [AVAILABLE_WIDTH * 0.50, AVAILABLE_WIDTH * 0.50]
story.extend(make_table(foda_data, foda_col, 'Tabla 2: Matriz FODA de Universo Nomada'))

story.append(body(
    'Del analisis FODA se desprenden tres conclusiones criticas que deben guiar la estrategia de automatizacion. '
    'Primero, las fortalezas actuales son poderosas pero no escalables en su formato manual; es imperativo '
    'transformar la cercania humana en un sistema que preserve la calidez pero elimine la dependencia de una sola '
    'persona para cada interaccion. Segundo, las oportunidades de mercado son significativas y urgentes: el turismo '
    'experiencial esta en auge y los competidores locales aun no han profesionalizado su presencia digital, lo que '
    'brinda una ventana de oportunidad que se cerrara en los proximos 12-18 meses. Tercero, la mayor amenaza no es '
    'la competencia directa, sino la incapacidad de escalar: si Universo Nomada no automatiza antes de crecer, el '
    'incremento de demanda colapsara los procesos manuales y destruira la experiencia del cliente.'
))

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# SECTION 3: PLAN DE AUTOMATIZACION
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
story.extend(add_major_section('3. Plan de Automatizacion de Procesos'))

story.append(body(
    'La automatizacion no significa reemplazar el toque humano que define a Universo Nomada, sino amplificarlo. '
    'Se trata de eliminar las tareas repetitivas y operativas que consumen el 70% del tiempo de trabajo diario, '
    'para que la energia creativa y relacional se concentre en lo que realmente genera valor: disenar experiencias '
    'unicas, construir relaciones con los clientes y cerrar ventas de alto valor. El siguiente plan se estructura '
    'en cuatro pilares fundamentales que deben implementarse de manera secuencial para maximizar el impacto.'
))

# 3.1
story.extend(add_subsection('3.1 Automatizacion de la Captacion de Leads'))

story.append(body(
    'Actualmente, los clientes llegan a Universo Nomada principalmente por recomendacion o redes sociales de forma '
    'organica. Si bien esto demuestra la calidad del servicio, es un canal limitado e impredecible. La primera '
    'prioridad es construir un embudo de captacion digital que funcione las 24 horas del dia, los 7 dias de la '
    'semana, generando un flujo constante de prospectos interesados en experiencias de viaje personalizadas en la '
    'region de Coquimbo y destinos seleccionados de Chile.'
))

story.append(body(
    '<b>Acciones especificas:</b> Crear landing pages optimizadas para cada tipo de experiencia (astronomia en '
    'Valle del Elqui, turismo costero, retiros de bienestar, aventura en montana). Cada landing page debe tener un '
    'formulario de contacto conectado automaticamente a un CRM, de modo que cada lead quede registrado y pueda ser '
    'segmentado por intereses, presupuesto y fecha de viaje estimada. Implementar chatbots con IA en el sitio web y '
    'en WhatsApp Business que respondan las preguntas frecuentes, recopilen datos del prospecto y agenden llamadas '
    'de seguimiento automaticamente. Configurar campanas de Google Ads y Meta Ads con segmentacion geografica '
    '(Chile) y por intereses (turismo experiencial, viajes a medida, naturaleza, astronomia), enviando el trafico '
    'directamente a las landing pages correspondientes.'
))

# 3.2
story.extend(add_subsection('3.2 Automatizacion del Funnel de Ventas'))

story.append(body(
    'Una vez captado el lead, es necesario nutrirlo automaticamente hasta que este listo para la cotizacion '
    'personalizada. Actualmente, este proceso depende enteramente de la memoria y disponibilidad de la fundadora, '
    'lo que genera retrasos, olvidos y perdida de clientes potenciales. La automatizacion del funnel de ventas '
    'permite que ningun prospecto se pierda y que cada uno reciba comunicaciones oportunas y relevantes sin '
    'intervencion manual constante.'
))

story.append(body(
    '<b>Acciones especificas:</b> Implementar secuencias de email automatizadas que se activen segun el comportamiento '
    'del prospecto: si visito la pagina de Valle del Elqui, recibe contenido sobre experiencias astronomicas; si '
    'abandono el formulario, recibe un recordatorio con testimonios; si completo el formulario, recibe un paquete '
    'de inspiracion con imagenes y relatos de viajes anteriores. Configurar un sistema de scoring de leads basado '
    'en interacciones: apertura de emails, clics en contenido, visitas repetidas al sitio, interacciones en '
    'redes sociales. Los leads con mayor puntuacion se asignan automaticamente para seguimiento telefonico '
    'prioritario. Crear templates de cotizacion semiautomatizados que la fundadora solo necesite personalizar '
    'con los detalles especificos del viaje, reduciendo el tiempo de cotizacion de horas a minutos.'
))

# 3.3
story.extend(add_subsection('3.3 Automatizacion Operativa y de Seguimiento'))

story.append(body(
    'La etapa post-venta es donde Universo Nomada brilla, pero tambien donde mas tiempo se consume. Las '
    'confirmaciones de reserva, los recordatorios de itinerario, las instrucciones de viaje, los pedidos de '
    'feedback y las solicitudes de resenas son tareas que pueden y deben automatizarse sin perder la calidez '
    'caracteristica de la marca. La clave esta en disenar comunicaciones automatizadas que parezcan personales, '
    'usando merge tags (nombre del cliente, destino, fecha) y un tono de voz consistente con la identidad de '
    'Universo Nomada.'
))

story.append(body(
    '<b>Acciones especificas:</b> Configurar emails automatizados pre-viaje con itinerario detallado, recomendaciones '
    'de equipaje, datos de contacto de emergencia y un mensaje personalizado de la fundadora. Implementar '
    'encuestas de satisfaccion automaticas post-viaje con enlace a Google Reviews o TripAdvisor. Crear un sistema '
    'de recordatorios automaticos para pagos pendientes, fechas limite de reserva y documentos necesarios. '
    'Automatizar la generacion de vouchers, facturas y comprobantes de pago. Configurar un programa de referidos '
    'automatizado que invite a los clientes satisfechos a recomendar Universo Nomada a cambio de descuentos en su '
    'proximo viaje, generando un ciclo virtuoso de captacion organica amplificada.'
))

# 3.4
story.extend(add_subsection('3.4 Automatizacion de Marketing de Contenidos'))

story.append(body(
    'El contenido es el combustible del embudo de captacion. Sin contenido relevante y frecuente, las landing pages '
    'no posicionan en Google, las campanas de ads no tienen donde enviar trafico de calidad y las redes sociales '
    'pierden relevancia. Sin embargo, producir contenido constantemente es una de las tareas mas demandantes para '
    'un equipo pequeno. La solucion es implementar un sistema de planificacion, produccion y distribucion de '
    'contenidos que maximice el alcance con el minimo esfuerzo operativo.'
))

story.append(body(
    '<b>Acciones especificas:</b> Crear un calendario editorial mensual con 8-12 piezas de contenido planificadas '
    'incluyendo blog posts, reels, stories, carouseles y newsletters. Utilizar IA generativa para producir '
    'borradores de articulos de blog sobre destinos, guias de viaje y relatos de experiencias que la fundadora '
    'luego edite y personalice con su voz autentica. Programar publicaciones automaticas en Instagram, Facebook y '
    'LinkedIn usando herramientas como Buffer o Later. Implementar un sistema de reciclaje de contenido: un relato '
    'de viaje se convierte en 5 stories, 1 reel, 1 post de blog, 1 email y 1 hilo en redes sociales, maximizando '
    'el retorno de cada pieza producida. Configurar SEO tecnico en el sitio web para posicionar organicamente '
    'terminos clave como "viajes personalizados Chile", "turismo experiencial La Serena", "Valle del Elqui tours".'
))

# Automation tools table
tools_data = [
    [Paragraph('<b>Proceso</b>', table_header_style),
     Paragraph('<b>Herramienta Recomendada</b>', table_header_style),
     Paragraph('<b>Funcion Automatizada</b>', table_header_style),
     Paragraph('<b>Inverscion Mensual Est.</b>', table_header_style)],
    [Paragraph('Captacion de leads', table_cell_style),
     Paragraph('HubSpot CRM (free) + Meta Ads', table_cell_style),
     Paragraph('Formularios, chatbot, CRM', table_cell_style),
     Paragraph('USD 0-50 + Ads budget', table_cell_center)],
    [Paragraph('Email marketing', table_cell_style),
     Paragraph('Mailchimp / Sendinblue', table_cell_style),
     Paragraph('Secuencias, nutricion, scoring', table_cell_style),
     Paragraph('USD 15-45', table_cell_center)],
    [Paragraph('Cotizaciones', table_cell_style),
     Paragraph('Proposify / Canva + Google Sheets', table_cell_style),
     Paragraph('Templates, auto-fill, seguimiento', table_cell_style),
     Paragraph('USD 0-25', table_cell_center)],
    [Paragraph('Redes sociales', table_cell_style),
     Paragraph('Buffer / Later', table_cell_style),
     Paragraph('Programacion, analisis, reciclaje', table_cell_style),
     Paragraph('USD 0-20', table_cell_center)],
    [Paragraph('Contenido con IA', table_cell_style),
     Paragraph('ChatGPT / Claude + Canva', table_cell_style),
     Paragraph('Borradores, imagenes, SEO', table_cell_style),
     Paragraph('USD 20-30', table_cell_center)],
    [Paragraph('WhatsApp Business', table_cell_style),
     Paragraph('WhatsApp Business API + ManyChat', table_cell_style),
     Paragraph('Respuestas auto, catalogo, seguimiento', table_cell_style),
     Paragraph('USD 0-15', table_cell_center)],
]
tools_col = [AVAILABLE_WIDTH * 0.20, AVAILABLE_WIDTH * 0.28, AVAILABLE_WIDTH * 0.30, AVAILABLE_WIDTH * 0.22]
story.extend(make_table(tools_data, tools_col, 'Tabla 3: Herramientas de automatizacion recomendadas e inversion estimada'))

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# SECTION 4: ESTRATEGIA DE VENTAS
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
story.extend(add_major_section('4. Estrategia para Incrementar Ventas en un 100%'))

story.append(body(
    'Duplicar las ventas no requiere duplicar el esfuerzo, sino rediseñar inteligentemente el sistema comercial. '
    'La estrategia se basa en tres palancas simultaneas: aumentar el volumen de prospectos que entran al embudo, '
    'mejorar la tasa de conversion de prospectos a clientes, y elevar el ticket promedio por venta. Si cada palanca '
    'mejora un 30%, el efecto combinado supera el 100% de crecimiento. A continuacion se detalla cada palanca con '
    'acciones concretas, metricas y plazos de implementacion.'
))

# 4.1
story.extend(add_subsection('4.1 Aumentar el Volumen de Prospectos (+30%)'))

story.append(body(
    'La primera palanca es cuantitativa: mas personas necesitan conocer Universo Nomada y entrar al embudo de '
    'ventas. Actualmente, la captacion es pasiva y dependiente del boca a boca. Para multiplicar el volumen de '
    'prospectos, es necesario activar canales digitales que generen un flujo predecible y medible de leads '
    'cualificados. La meta es pasar de recibir 10-15 consultas mensuales orgánicas a generar 40-50 leads mensuales '
    'a traves de canales combinados, manteniendo un costo por lead inferior a USD 5.'
))

story.append(body(
    '<b>Acciones:</b> Lanzar campanas de Google Ads con keywords de largo recorrido ("tour astronomia Valle del '
    'Elqui desde La Serena", "viaje personalizado norte de Chile"). Implementar campanas de Meta Ads con lookalike '
    'audiences basadas en los mejores clientes actuales. Crear alianzas con hoteles boutique, restaurantes y '
    'operadores turisticos complementarios en La Serena para intercambio de leads. Activar un programa de referidos '
    'con incentivos atractivos (10% descuento por cada referral que concrete viaje). Publicar contenido SEO en el '
    'blog semanalmente para captar trafico organico de alto valor. Registrarse en directorios turisticos de la '
    'region y plataformas especializadas en turismo experiencial.'
))

# 4.2
story.extend(add_subsection('4.2 Mejorar la Tasa de Conversion (+30%)'))

story.append(body(
    'Tener mas prospectos no sirve de nada si no se convierten en clientes. Actualmente, la tasa de conversion '
    'estimada de consulta a venta puede estar entre el 15-25%, lo que es razonable para turismo de alto valor pero '
    'tiene un margen significativo de mejora. Las principales causas de perdida son: tiempos de respuesta lentos, '
    'falta de seguimiento sistematico, cotizaciones que no transmiten el valor diferencial de la experiencia, y '
    'ausencia de prueba social automatizada (testimonios, resenas, casos de exito) en el momento de la decision.'
))

story.append(body(
    '<b>Acciones:</b> Implementar una regla de respuesta en menos de 2 horas usando WhatsApp Business con '
    'respuestas automaticas inteligentes y derivacion al Ing. Comercial para seguimiento. Crear un portfolio de '
    'experiencias con testimonios en video, fotos profesionales y relatos de clientes anteriores que se envien '
    'automaticamente despues de la primera consulta. Disenar un proceso de cotizacion en 3 niveles: experiencia '
    'esencial, experiencia premium y experiencia exclusiva, usando anclaje de precios para que la opcion intermedia '
    'parezca la mas atractiva. Entrenar al equipo en tecnicas de cierre consultivo: en lugar de preguntar '
    '"le gusta esta opcion?", preguntar "si pudiera viajar en estas fechas con este itinerario, que le gustaria '
    'ajustar?". Esta tecnica compromete al prospecto y revela objeciones reales.'
))

# 4.3
story.extend(add_subsection('4.3 Elevar el Ticket Promedio (+30%)'))

story.append(body(
    'El ticket promedio es la palanca mas rentable porque no requiere mas prospectos ni mas conversiones, sino '
    'vender mas valor a los clientes que ya decidieron comprar. En turismo experiencial, el upselling y el '
    'cross-selling son naturales: el cliente que quiere un tour al Valle del Elqui probablemente este dispuesto a '
    'pagar por una experiencia gastronomica adicional, una noche extra en un observatorio, o un traslado premium. '
    'La clave es ofrecer estas opciones en el momento adecuado del proceso de compra, no como un add-on generico '
    'sino como una recomendacion personalizada que enriquece la experiencia.'
))

story.append(body(
    '<b>Acciones:</b> Disenar paquetes escalonados con anclaje de precio: mostrar siempre una opcion premium '
    'antes de la estandar para redefinir la percepcion de valor. Crear un catalogo de "experiencias complementarias" '
    'que se ofrezcan automaticamente despues de la cotizacion base (cena bajo las estrellas, sesion de fotografía '
    'profesional, guia privado, traslados VIP). Implementar upselling temporal: "si reserva en los proximos 7 dias, '
    'incluimos una experiencia sorpresa gratuita". Ofrecer paquetes multi-destino con descuento escalonado: si el '
    'cliente viaja a dos destinos, el segundo tiene 15% de descuento. Crear membresia "Nomada Premium" con '
    'beneficios exclusivos (acceso anticipado a nuevos destinos, descuentos permanentes, experiencia de bienvenida) '
    'que genere ingresos recurrentes y fidelice a los mejores clientes.'
))

# Growth metrics table
growth_data = [
    [Paragraph('<b>Palanca</b>', table_header_style),
     Paragraph('<b>Metrica Actual (Est.)</b>', table_header_style),
     Paragraph('<b>Meta a 6 Meses</b>', table_header_style),
     Paragraph('<b>Impacto en Ventas</b>', table_header_style)],
    [Paragraph('Volumen de prospectos', table_cell_style),
     Paragraph('10-15 leads/mes', table_cell_center),
     Paragraph('40-50 leads/mes', table_cell_center),
     Paragraph('+30% facturacion', table_cell_center)],
    [Paragraph('Tasa de conversion', table_cell_style),
     Paragraph('15-25%', table_cell_center),
     Paragraph('30-40%', table_cell_center),
     Paragraph('+30% facturacion', table_cell_center)],
    [Paragraph('Ticket promedio', table_cell_style),
     Paragraph('USD 300-500', table_cell_center),
     Paragraph('USD 450-750', table_cell_center),
     Paragraph('+30% facturacion', table_cell_center)],
    [Paragraph('<b>Efecto combinado</b>', table_cell_style),
     Paragraph('-', table_cell_center),
     Paragraph('-', table_cell_center),
     Paragraph('<b>+100%+ facturacion</b>', table_cell_center)],
]
growth_col = [AVAILABLE_WIDTH * 0.25, AVAILABLE_WIDTH * 0.22, AVAILABLE_WIDTH * 0.22, AVAILABLE_WIDTH * 0.31]
story.extend(make_table(growth_data, growth_col, 'Tabla 4: Proyeccion de crecimiento por palanca comercial'))

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# SECTION 5: ROL DEL INGENIERO COMERCIAL
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
story.extend(add_major_section('5. Rol del Ingeniero Comercial en Universo Nomada'))

story.append(body(
    'La incorporacion de un Ingeniero Comercial al equipo de Universo Nomada no es simplemente sumar una persona '
    'mas al negocio: es una transformacion estructural que profesionaliza la funcion comercial y permite escalar '
    'las operaciones de manera sostenible. Como Ingeniero Comercial, tu formación te dota de habilidades en analisis '
    'de mercado, estrategia de precios, gestion de clientes clave, negociacion y modelado financiero, todas '
    'competencias que son criticas para llevar Universo Nomada al siguiente nivel de crecimiento.'
))

# 5.1
story.extend(add_subsection('5.1 Division Estrategica de Roles'))

story.append(body(
    'La clave del exito en un equipo de dos personas es la especializacion clara de roles, evitando la duplicacion '
    'de esfuerzos y asegurando que cada persona se enfoque en lo que mejor sabe hacer. La fundadora es la cara '
    'creativa y experiencial de la marca; ella diseña las experiencias, conoce los destinos, construye las '
    'relaciones con proveedores locales y garantiza la calidad del producto. El Ingeniero Comercial es el motor '
    'de crecimiento: captura prospectos, gestiona el embudo de ventas, analiza datos, optimiza precios y cierra '
    'negocios. Esta division no es rigida, pero debe ser la regla general que guie la operacion diaria.'
))

roles_data = [
    [Paragraph('<b>Area</b>', table_header_style),
     Paragraph('<b>Fundadora</b>', table_header_style),
     Paragraph('<b>Ingeniero Comercial</b>', table_header_style)],
    [Paragraph('Diseno de experiencias', table_cell_style),
     Paragraph('Lider: selecciona destinos, crea itinerarios, negocia con proveedores', table_cell_style),
     Paragraph('Apoyo: analiza demanda, sugiere ajustes basados en datos de mercado', table_cell_style)],
    [Paragraph('Captacion de clientes', table_cell_style),
     Paragraph('Apoyo: genera contenido autentico, redes sociales, relaciones', table_cell_style),
     Paragraph('Lider: campanas digitales, SEO/ADS, alianzas, programa de referidos', table_cell_style)],
    [Paragraph('Gestion de ventas', table_cell_style),
     Paragraph('Apoyo: cotizacion especializada, cierre de alto valor', table_cell_style),
     Paragraph('Lider: CRM, seguimiento, nutricion de leads, metricas de conversion', table_cell_style)],
    [Paragraph('Precios y rentabilidad', table_cell_style),
     Paragraph('Apoyo: aporta costos reales y percepcion de valor', table_cell_style),
     Paragraph('Lider: estrategia de precios, margenes, upselling, anclaje', table_cell_style)],
    [Paragraph('Atencion post-venta', table_cell_style),
     Paragraph('Lider: acompanamiento personal, feedback, relacion a largo plazo', table_cell_style),
     Paragraph('Apoyo: automatizacion de encuestas, programa de referidos, analisis', table_cell_style)],
    [Paragraph('Analisis y estrategia', table_cell_style),
     Paragraph('Apoyo: vision del negocio, intuicion del mercado', table_cell_style),
     Paragraph('Lider: KPIs, dashboards, analisis de rentabilidad, planificacion', table_cell_style)],
]
roles_col = [AVAILABLE_WIDTH * 0.20, AVAILABLE_WIDTH * 0.40, AVAILABLE_WIDTH * 0.40]
story.extend(make_table(roles_data, roles_col, 'Tabla 5: Division de roles entre la fundadora y el Ingeniero Comercial'))

# 5.2
story.extend(add_subsection('5.2 Funciones Especificas del Ing. Comercial'))

story.append(body(
    '<b>Gestion del CRM y pipeline de ventas:</b> Ser el dueno del CRM (HubSpot gratuito para empezar). Cada lead '
    'que entra, cada interaccion, cada cotizacion y cada cierre debe quedar registrado. Esto permite analizar '
    'tendencias, identificar cuellos de botella, predecir ingresos y tomar decisiones basadas en datos reales. '
    'Sin datos, no hay optimizacion. El CRM es la base de todo el sistema comercial automatizado.'
))

story.append(body(
    '<b>Prospectacion activa y alianzas B2B:</b> No esperar a que los clientes lleguen solos. Identificar '
    'activamente oportunidades de alianza con hoteles boutique, restaurantes premium, centros de bienestar y '
    'operadores complementarios en La Serena y la region. Tambien explorar convenios con empresas para viajes '
    'corporativos de team building o retiros ejecutivos, un segmento de alto valor que paga bien y repite. La '
    'prospectacion B2B genera un flujo de ingresos mas predecible y con tickets promedios mas altos que el '
    'segmento B2C individual.'
))

story.append(body(
    '<b>Optimizacion de precios y rentabilidad:</b> Aplicar tu formacion en economia y finanzas para disenar '
    'una estructura de precios que maximice el margen sin perder competitividad. Implementar pricing dinamico '
    'basado en temporada, demanda anticipada y disponibilidad. Calcular el costo total de cada experiencia '
    '(incluyendo tiempo operativo) para asegurar que cada venta sea rentable. Desarrollar modelos de escenarios '
    'para evaluar el impacto de descuentos, promociones y paquetes combinados en la rentabilidad global.'
))

story.append(body(
    '<b>Analisis de mercado y competencia:</b> Monitorear constantemente lo que hacen los competidores en La Serena '
    'y la region: precios, experiencias ofrecidas, canales de captacion, presencia digital. Identificar brechas '
    'en el mercado que Universo Nomada pueda llenar antes que nadie. Analizar tendencias de busqueda en Google '
    'Trends para anticipar que destinos y experiencias estan ganando interes y ajustar la oferta oportunamente. '
    'Este trabajo de inteligencia comercial es invisible para el cliente pero determinante para la ventaja '
    'competitiva sostenida del negocio.'
))

story.append(body(
    '<b>Dashboard de gestion y KPIs:</b> Construir un tablero de control semanal que muestre los indicadores '
    'clave del negocio: leads generados, tasa de conversion, ticket promedio, margen promedio, satisfaccion del '
    'cliente, costo de adquisicion de cliente (CAC), valor de vida del cliente (LTV), y ratio LTV/CAC. Este '
    'dashboard debe ser revisado semanalmente entre ambos socios para tomar decisiones operativas informadas y '
    'corregir el rumbo cuando las metricas se desvian del objetivo.'
))

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# SECTION 6: HOJA DE RUTA 90 DIAS
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
story.extend(add_major_section('6. Hoja de Ruta: Plan de Accion a 90 Dias'))

story.append(body(
    'La implementacion exitosa de la estrategia requiere un enfoque por fases que permita construir sobre bases '
    'solidas sin abrumar al equipo con cambios simultaneos. El plan a 90 dias se divide en tres fases de 30 dias '
    'cada una, con entregables claros y metricas de exito para cada fase. Este enfoque incremental permite ir '
    'automatizando mientras se siguen atendiendo clientes y generando ingresos, evitando la parálisis operativa '
    'que podria causar un rediseño integral de golpe.'
))

# Phase 1
story.extend(add_subsection('6.1 Fase 1: Fundamentos (Dias 1-30)'))

story.append(body(
    'El primer mes se dedica a sentar las bases del sistema comercial automatizado. Sin estas bases, ninguna '
    'estrategia posterior funcionara de manera sostenida. La prioridad es implementar el CRM, configurar los '
    'canales de captacion basicos y profesionalizar la presencia digital. Al finalizar esta fase, cada lead '
    'que entre debera quedar registrado automaticamente, y deberias tener visibilidad completa del pipeline de '
    'ventas por primera vez en la historia del negocio.'
))

phase1_data = [
    [Paragraph('<b>Semana</b>', table_header_style),
     Paragraph('<b>Accion</b>', table_header_style),
     Paragraph('<b>Responsable</b>', table_header_style),
     Paragraph('<b>Entregable</b>', table_header_style)],
    [Paragraph('1', table_cell_center),
     Paragraph('Configurar HubSpot CRM gratuito', table_cell_style),
     Paragraph('Ing. Comercial', table_cell_style),
     Paragraph('CRM operativo con pipeline de 5 etapas', table_cell_style)],
    [Paragraph('1', table_cell_center),
     Paragraph('Auditar presencia digital actual', table_cell_style),
     Paragraph('Ambos', table_cell_style),
     Paragraph('Informe de brechas y oportunidades', table_cell_style)],
    [Paragraph('2', table_cell_center),
     Paragraph('Crear 3 landing pages de experiencias', table_cell_style),
     Paragraph('Ing. Comercial', table_cell_style),
     Paragraph('LPs conectadas al CRM', table_cell_style)],
    [Paragraph('2', table_cell_center),
     Paragraph('Configurar WhatsApp Business API', table_cell_style),
     Paragraph('Ing. Comercial', table_cell_style),
     Paragraph('Chatbot con respuestas automaticas', table_cell_style)],
    [Paragraph('3', table_cell_center),
     Paragraph('Disenar templates de cotizacion', table_cell_style),
     Paragraph('Fundadora + IC', table_cell_style),
     Paragraph('3 templates (esencial, premium, exclusivo)', table_cell_style)],
    [Paragraph('3', table_cell_center),
     Paragraph('Crear portfolio digital con testimonios', table_cell_style),
     Paragraph('Fundadora', table_cell_style),
     Paragraph('PDF interactivo con casos de exito', table_cell_style)],
    [Paragraph('4', table_cell_center),
     Paragraph('Lanzar primera campana Meta Ads', table_cell_style),
     Paragraph('Ing. Comercial', table_cell_style),
     Paragraph('Campana activa con presupuesto USD 100', table_cell_style)],
    [Paragraph('4', table_cell_center),
     Paragraph('Configurar email marketing basico', table_cell_style),
     Paragraph('Ing. Comercial', table_cell_style),
     Paragraph('3 secuencias automatizadas activas', table_cell_style)],
]
phase1_col = [AVAILABLE_WIDTH * 0.10, AVAILABLE_WIDTH * 0.35, AVAILABLE_WIDTH * 0.22, AVAILABLE_WIDTH * 0.33]
story.extend(make_table(phase1_data, phase1_col, 'Tabla 6: Plan de accion Fase 1 - Fundamentos'))

# Phase 2
story.extend(add_subsection('6.2 Fase 2: Escalamiento (Dias 31-60)'))

story.append(body(
    'Con las bases operativas funcionando, el segundo mes se enfoca en escalar los canales de captacion, optimizar '
    'las tasas de conversion basandose en los datos recopilados en la Fase 1, y comenzar a implementar las '
    'estrategias de upselling y cross-selling. Es el momento de analizar los primeros resultados, ajustar lo que '
    'no funciona y potenciar lo que si. La meta al finalizar esta fase es haber multiplicado por 2-3x el volumen '
    'de leads entrantes y haber mejorado la tasa de conversion en al menos 5 puntos porcentuales.'
))

story.append(body(
    '<b>Acciones clave:</b> Escalar presupuesto de ads basado en ROAS (retorno sobre inversion publicitaria) de '
    'la Fase 1. Lanzar campanas de Google Ads con keywords de largo recorrido. Implementar programa de referidos '
    'con sistema automatizado de seguimiento y recompensas. Crear alianzas con 3-5 hoteles y restaurantes boutique '
    'de La Serena para intercambio de leads. Iniciar publicacion de contenido SEO semanal en el blog. Configurar '
    'encuestas automaticas post-viaje y solicitar activamente resenas en Google y TripAdvisor. Comenzar a probar '
    'upselling en las cotizaciones con las experiencias complementarias disenadas.'
))

# Phase 3
story.extend(add_subsection('6.3 Fase 3: Optimizacion (Dias 61-90)'))

story.append(body(
    'El tercer mes es donde se consolida el sistema y se optimiza basandose en datos reales. Todas las piezas '
    'deben estar funcionando de manera integrada: captacion, nutricion, conversion, post-venta y referidos. '
    'El objetivo es alcanzar un flujo comercial predecible y sostenible que funcione con minima intervencion '
    'manual en las tareas operativas, liberando tiempo para la creatividad, las relaciones y la estrategia.'
))

story.append(body(
    '<b>Acciones clave:</b> Analizar datos de 60 dias y ajustar estrategia de precios, canales y mensajes. '
    'Implementar pricing dinamico basado en temporada y demanda. Lanzar programa "Nomada Premium" de membresia. '
    'Crear dashboard de KPIs automatizado para revision semanal. Evaluar resultados de alianzas B2B y escalar '
    'las mas rentables. Iniciar prospeccion de segmento corporativo (retiros, team building). Refinar las '
    'secuencias de email basandose en tasas de apertura y clic reales. Documentar todos los procesos para que '
    'cualquier miembro del equipo pueda operar el sistema. Evaluar contratar asistencia part-time para tareas '
    'administrativas si el volumen lo justifica.'
))

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# SECTION 7: HERRAMIENTAS Y PLATAFORMAS
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
story.extend(add_major_section('7. Ecosistema de Herramientas Recomendadas'))

story.append(body(
    'Seleccionar las herramientas adecuadas es tan importante como la estrategia misma. Un ecosistema de '
    'herramientas mal integrado genera mas trabajo manual, no menos. Los criterios de seleccion son: facilidad de '
    'implementacion (el equipo debe poder configurarlas sin desarrolladores), integracion nativa entre si (para '
    'evitar silos de datos), escalabilidad (que sirvan cuando el negocio crezca 5x), y costo razonable para un '
    'emprendimiento en fase de crecimiento. A continuacion se presenta el stack recomendado organizado por funcion.'
))

stack_data = [
    [Paragraph('<b>Funcion</b>', table_header_style),
     Paragraph('<b>Herramienta</b>', table_header_style),
     Paragraph('<b>Plan</b>', table_header_style),
     Paragraph('<b>Costo/mes</b>', table_header_style),
     Paragraph('<b>Prioridad</b>', table_header_style)],
    [Paragraph('CRM y pipeline', table_cell_style),
     Paragraph('HubSpot CRM', table_cell_style),
     Paragraph('Free Starter', table_cell_center),
     Paragraph('USD 0', table_cell_center),
     Paragraph('Inmediata', table_cell_center)],
    [Paragraph('Email marketing', table_cell_style),
     Paragraph('Mailchimp', table_cell_style),
     Paragraph('Essentials', table_cell_center),
     Paragraph('USD 13-45', table_cell_center),
     Paragraph('Inmediata', table_cell_center)],
    [Paragraph('Landing pages', table_cell_style),
     Paragraph('HubSpot / Carrd', table_cell_style),
     Paragraph('Free / Pro', table_cell_center),
     Paragraph('USD 0-19', table_cell_center),
     Paragraph('Inmediata', table_cell_center)],
    [Paragraph('Chatbot WhatsApp', table_cell_style),
     Paragraph('ManyChat', table_cell_style),
     Paragraph('Pro', table_cell_center),
     Paragraph('USD 15', table_cell_center),
     Paragraph('Semana 2', table_cell_center)],
    [Paragraph('Redes sociales', table_cell_style),
     Paragraph('Buffer', table_cell_style),
     Paragraph('Free / Essentials', table_cell_center),
     Paragraph('USD 0-6', table_cell_center),
     Paragraph('Semana 3', table_cell_center)],
    [Paragraph('Diseno visual', table_cell_style),
     Paragraph('Canva Pro', table_cell_style),
     Paragraph('Pro', table_cell_center),
     Paragraph('USD 13', table_cell_center),
     Paragraph('Inmediata', table_cell_center)],
    [Paragraph('Cotizaciones', table_cell_style),
     Paragraph('Proposify / Canva', table_cell_style),
     Paragraph('Free / Pro', table_cell_center),
     Paragraph('USD 0-13', table_cell_center),
     Paragraph('Semana 3', table_cell_center)],
    [Paragraph('Ads digitales', table_cell_style),
     Paragraph('Meta Ads + Google Ads', table_cell_style),
     Paragraph('Pay per click', table_cell_center),
     Paragraph('USD 200-500', table_cell_center),
     Paragraph('Semana 4', table_cell_center)],
    [Paragraph('Analisis web', table_cell_style),
     Paragraph('Google Analytics 4', table_cell_style),
     Paragraph('Free', table_cell_center),
     Paragraph('USD 0', table_cell_center),
     Paragraph('Inmediata', table_cell_center)],
    [Paragraph('Contenido con IA', table_cell_style),
     Paragraph('ChatGPT Plus', table_cell_style),
     Paragraph('Plus', table_cell_center),
     Paragraph('USD 20', table_cell_center),
     Paragraph('Inmediata', table_cell_center)],
]
stack_col = [AVAILABLE_WIDTH * 0.17, AVAILABLE_WIDTH * 0.25, AVAILABLE_WIDTH * 0.17, AVAILABLE_WIDTH * 0.18, AVAILABLE_WIDTH * 0.23]
story.extend(make_table(stack_data, stack_col, 'Tabla 7: Ecosistema de herramientas recomendado'))

story.append(body(
    'La inversion total estimada en herramientas ronda los USD 60-100 mensuales (sin incluir el presupuesto de '
    'publicidad). Es una inversion extraordinariamente baja comparada con el retorno esperado: cada dolar invertido '
    'en automatizacion y captacion digital deberia generar al menos USD 5-10 en nuevas ventas durante los primeros '
    '6 meses, y aun mas a medida que los canales maduran y los costos de adquisicion disminuyen por la economia '
    'de escala y la acumulacion de datos de campanas.'
))

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# SECTION 8: KPIs Y METRICAS
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
story.extend(add_major_section('8. Metricas y KPIs de Seguimiento'))

story.append(body(
    'Lo que no se mide, no se puede mejorar. El sistema de metricas es el sistema nervioso del negocio: permite '
    'detectar problemas antes de que se conviertan en crisis, identificar oportunidades antes que la competencia, '
    'y tomar decisiones con confianza basada en datos reales. A continuacion se definen los KPIs esenciales que '
    'deben monitorearse semanalmente, sus valores objetivo y las acciones correctivas sugeridas cuando las metricas '
    'se desvian del rango esperado.'
))

kpi_data = [
    [Paragraph('<b>KPI</b>', table_header_style),
     Paragraph('<b>Como Medir</b>', table_header_style),
     Paragraph('<b>Objetivo</b>', table_header_style),
     Paragraph('<b>Frecuencia</b>', table_header_style)],
    [Paragraph('Leads mensuales', table_cell_style),
     Paragraph('CRM: nuevos contactos ingresados', table_cell_style),
     Paragraph('40-50/mes', table_cell_center),
     Paragraph('Semanal', table_cell_center)],
    [Paragraph('Tasa de conversion', table_cell_style),
     Paragraph('CRM: leads que cerraron / total leads', table_cell_style),
     Paragraph('30-40%', table_cell_center),
     Paragraph('Semanal', table_cell_center)],
    [Paragraph('Ticket promedio', table_cell_style),
     Paragraph('Ingresos totales / numero de ventas', table_cell_style),
     Paragraph('USD 450-750', table_cell_center),
     Paragraph('Mensual', table_cell_center)],
    [Paragraph('CAC (Costo Adquisicion)', table_cell_style),
     Paragraph('Gasto marketing / clientes nuevos', table_cell_style),
     Paragraph('Menos USD 50', table_cell_center),
     Paragraph('Mensual', table_cell_center)],
    [Paragraph('LTV (Valor de Vida)', table_cell_style),
     Paragraph('Ticket promedio x compras promedio x anos', table_cell_style),
     Paragraph('Mayor USD 1,500', table_cell_center),
     Paragraph('Trimestral', table_cell_center)],
    [Paragraph('LTV/CAC Ratio', table_cell_style),
     Paragraph('LTV dividido por CAC', table_cell_style),
     Paragraph('Mayor 3:1', table_cell_center),
     Paragraph('Trimestral', table_cell_center)],
    [Paragraph('Tiempo respuesta lead', table_cell_style),
     Paragraph('CRM: tiempo entre ingreso y primera respuesta', table_cell_style),
     Paragraph('Menos 2 horas', table_cell_center),
     Paragraph('Semanal', table_cell_center)],
    [Paragraph('NPS / Satisfaccion', table_cell_style),
     Paragraph('Encuesta post-viaje automatica', table_cell_style),
     Paragraph('Mayor 70', table_cell_center),
     Paragraph('Post-viaje', table_cell_center)],
    [Paragraph('Tasa de referidos', table_cell_style),
     Paragraph('Clientes que refieren / total clientes', table_cell_style),
     Paragraph('Mayor 25%', table_cell_center),
     Paragraph('Mensual', table_cell_center)],
    [Paragraph('ROAS (Ads)', table_cell_style),
     Paragraph('Ingresos por ads / gasto en ads', table_cell_style),
     Paragraph('Mayor 4:1', table_cell_center),
     Paragraph('Semanal', table_cell_center)],
]
kpi_col = [AVAILABLE_WIDTH * 0.20, AVAILABLE_WIDTH * 0.33, AVAILABLE_WIDTH * 0.22, AVAILABLE_WIDTH * 0.25]
story.extend(make_table(kpi_data, kpi_col, 'Tabla 8: KPIs esenciales y objetivos de rendimiento'))

story.append(body(
    'Es fundamental que la revision de KPIs se convierta en un ritual semanal no negociable. Cada lunes por la '
    'manana, ambos socios deben revisar el dashboard durante 30 minutos, celebrar los avances, identificar las '
    'metricas que estan por debajo del objetivo y definir una accion correctiva concreta para cada una. Este '
    'habito es la diferencia entre un negocio que crece de manera planificada y uno que reacciona a las crisis '
    'cuando ya es tarde. La disciplina en el seguimiento de metricas es tan importante como la estrategia misma.'
))

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# SECTION 9: VENTAJA COMPETITIVA LOCAL - LA SERENA
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
story.extend(add_major_section('9. Ventaja Competitiva Local: La Serena y Region de Coquimbo'))

story.append(body(
    'Ubicarse en La Serena no es casualidad ni una limitacion: es una ventaja competitiva estrategica que debe '
    'aprovecharse al maximo. La Region de Coquimbo concentra algunos de los atractivos turisticos mas potentes '
    'de Chile: el Valle del Elqui (reconocido mundialmente por la observacion astronomica y la produccion de '
    'pisco), la Reserva Nacional Pinguino de Humboldt, los pintorescos pueblos del interior como Vicuna y '
    'Paihuano, la gastronomia marina de la costa, y un clima privilegiado con mas de 300 dias despejados al ano. '
    'Estos atractivos naturales, combinados con la propuesta experiencial de Universo Nomada, crean una oferta '
    'dificil de replicar por agencias ubicadas en Santiago u otras regiones.'
))

story.append(body(
    '<b>Estrategias locales:</b> Desarrollar experiencias exclusivas que solo alguien radicado en La Serena puede '
    'ofrecer: acceso a observatorios privados con astronomos locales, cenas con productores de pisco en el valle, '
    'paseos en bote con pescadores artesanales, caminatas guiadas por senderos poco conocidos de la cordillera. '
    'Estas experiencias "insider" son el nucleo de la diferenciacion y deben protagonizar el contenido de marketing '
    'y las landing pages. Ademas, la presencia fisica en La Serena permite alianzas directas con proveedores '
    'locales, negociando mejores tarifas y condiciones exclusivas que las agencias remotas no pueden obtener, '
    'mejorando asi tanto los margenes como la calidad de la experiencia ofrecida al cliente final.'
))

story.append(body(
    'La Serena tambien tiene un flujo turistico estacional muy marcado, con alta temporada en verano (diciembre a '
    'febrero) y durante feriados largos. Esto debe considerarse en la estrategia de precios y captacion: los '
    'esfuerzos de marketing deben intensificarse 2-3 meses antes de cada pico de demanda, y los precios deben '
    'ajustarse dinamicamente segun la ocupacion proyectada. Ademas, es fundamental desarrollar ofertas para la '
    'baja temporada (turismo de bienestar, retiros, astronomia en invierno cuando el cielo es mas claro) que '
    'permitan mantener un flujo de ingresos mas estable durante todo el ano, reduciendo la vulnerabilidad ante '
    'la estacionalidad y aprovechando las condiciones unicas de cada estacion en la region.'
))

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# BUILD DOCUMENT
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
doc.multiBuild(story)

print(f"Body PDF generated: {BODY_PDF}")
